repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        description: black
        entry: env -i PATH=./.venv/bin python3 -m black
        language: python
        types: [python]

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: flake8
        entry: env -i PATH=./.venv/bin python3 -m flake8
        language: python
        types: [python]

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        description: mypy
        entry: env -i PATH=./.venv/bin python3 -m mypy
        language: python
        types: [python]
