version: '3.8'
services:

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/configs:/etc/nginx/conf.d

  admin-movies:
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/opt/app
      - ./docker/django/entrypoint.sh:/usr/local/bin/entrypoint.sh

  database:
    ports:
      - "5432:5432"
