# Generated by Django 4.2.11 on 2024-11-30 12:39

import django.core.validators
from django.db import (
    migrations,
    models,
)
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA content',
            reverse_sql='DROP SCHEMA content',
        ),
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255,
                        verbose_name='Title',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name='Description',
                    ),
                ),
                (
                    'creation_date',
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name='Creation Date',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            (
                                'movie',
                                'Movie',
                            ),
                            (
                                'tv_show',
                                'TV Show',
                            ),
                        ],
                        max_length=127,
                        verbose_name='Type',
                    ),
                ),
                (
                    'rating',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='Rating',
                    ),
                ),
                (
                    'file_path',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='',
                        verbose_name='File path',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Film Work',
                'verbose_name_plural': 'Film Works',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255,
                        verbose_name='Name',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name='Description',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'full_name',
                    models.CharField(
                        max_length=255,
                        verbose_name='Full Name',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonFilmWork',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            (
                                'producer',
                                'Producer',
                            ),
                            (
                                'actor',
                                'Actor',
                            ),
                            (
                                'writer',
                                'Writer',
                            ),
                            (
                                'director',
                                'Director',
                            ),
                        ],
                        max_length=127,
                        null=True,
                        verbose_name='Role',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'film_work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='movies.filmwork',
                        verbose_name='Film work',
                    ),
                ),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='movies.person',
                        verbose_name='Person',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'content"."person_film_work',
            },
        ),
        migrations.CreateModel(
            name='GenreFilmWork',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'film_work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='movies.filmwork',
                        verbose_name='Film work',
                    ),
                ),
                (
                    'genre',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='movies.genre',
                        verbose_name='Genre',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'content"."genre_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(
                through='movies.GenreFilmWork',
                to='movies.genre',
            ),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(
                through='movies.PersonFilmWork',
                to='movies.person',
            ),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(
                fields=(
                    'person',
                    'film_work',
                    'role',
                ),
                name='person_film_work_role_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(
                fields=(
                    'film_work',
                    'genre',
                ),
                name='genre_film_work_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(
                fields=['creation_date'],
                name='film_work_creation_date_idx',
            ),
        ),
    ]
